[project]
name = "theshadowfile"
version = "0.1.0"
description = "Hide and extract secret text messages within image files."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "fastapi[standard]>=0.128.0",
    "pillow>=12.1.0",
]
